name: Pull Request Creation

on:
  push:
    branches:
      - all

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: marouaneYATIME
        id: get_pull_requests
        with:
          query: |
            query user(login: "marouaneYATIME") {
              pullRequests(last: 100, orderBy: {field: CREATED_AT, direction: DESC}) {
                totalCount
                nodes {
                  title
                  url
                  state
                  mergedBy {
                    avatarUrl
                    url
                    login
                  }
                  createdAt
                  number
                  changedFiles
                  additions
                  deletions
                  baseRepository {
                    name
                    url
                    owner {
                      avatarUrl
                      login
                      url
                    }
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'Pull Requests Data: ${{ steps.get_latest_release.outputs.data }}'"
